import type { KnowledgeEntry } from "../../types/knowledge";

function entry(id: string, name: string, category: string, definition: string, impact: string, remediation: string): KnowledgeEntry {
  return { id, name, category, definition, indicators: ["Unexpected behavior in an authorized test flow", "Missing server-side control or validation", "A reproducible difference between intended and actual behavior", "An expected boundary or policy is not enforced"], evidenceChecklist: ["Record the affected asset and endpoint", "Capture the minimum authorized request, response, or UI evidence", "Document the role, tenant, or environment used", "Record expected versus actual behavior", "Redact tokens, private records, and unrelated identifiers"], reportQuestions: ["What is affected and under which authorized conditions?", "Which role, account, tenant, or client context was used?", "What exact expected control or behavior should have applied?", "What evidence verifies the observation reliably?", "Who or what could be affected if it is not remediated?", "Which defensive control should be verified after remediation?"], impactGuidance: impact, remediationGuidance: remediation, suggestedSections: ["Executive Summary", "Technical Description", "Prerequisites", "Steps to Reproduce", "Security Impact", "Recommended Remediation"], references: [{ label: "OWASP Web Security Testing Guide", url: "https://owasp.org/www-project-web-security-testing-guide/" }], tags: [category, name], isBuiltIn: true };
}

export const BUILT_IN_KNOWLEDGE: KnowledgeEntry[] = [
  entry("kb-xss", "Cross-Site Scripting", "Injection", "Untrusted input is rendered in a browser context without appropriate output handling.", "Describe the affected user context, browser-side consequence, and realistic data or action exposure.", "Use context-aware output encoding, validate input, and apply an appropriate Content Security Policy."),
  entry("kb-idor", "Broken Access Control / IDOR", "Authorization", "An object can be accessed or modified without a valid server-side authorization decision.", "Describe cross-user or cross-tenant data and action exposure.", "Enforce ownership and authorization checks for every server-side object access."),
  entry("kb-auth", "Authentication Bypass", "Authentication", "A protected workflow is reachable without the intended authentication control.", "Describe the protected capability or account context that becomes accessible.", "Apply authentication checks consistently at the server-side boundary."),
  entry("kb-disclosure", "Information Disclosure", "Data Exposure", "Sensitive or internal information is exposed to an unauthorized audience.", "Explain how the exposed details affect privacy, security posture, or follow-on risk.", "Minimize returned data and enforce audience-appropriate access controls."),
  entry("kb-misconfig", "Security Misconfiguration", "Configuration", "An unsafe configuration exposes behavior beyond the intended security boundary.", "Describe the scope and practical consequence of the exposed configuration.", "Use secure defaults, restrict exposure, and validate configuration continuously."),
  entry("kb-ssrf", "Server-Side Request Forgery", "Server-Side Request Forgery", "A server-side feature accepts an unintended request destination.", "Describe reachable internal resources or trust-boundary impact without exceeding authorized testing scope.", "Use destination allowlists, block private ranges, and enforce egress controls."),
  entry("kb-redirect", "Open Redirect", "Validation", "A redirect flow accepts an untrusted external destination.", "Describe credible trust, phishing, or authentication-flow consequences.", "Allow only approved destinations or map redirect options server-side."),
  entry("kb-csrf", "Cross-Site Request Forgery", "Request Integrity", "A state-changing action lacks adequate request-origin protection.", "Describe the affected user action and account impact.", "Use anti-CSRF controls, same-site cookies, and origin validation."),
  entry("kb-rate", "Rate Limit Weakness", "Abuse Prevention", "A sensitive operation lacks appropriate throttling or abuse controls.", "Describe business, account, or service impact using authorized and non-destructive evidence.", "Use rate limits, monitoring, and risk-based controls."),
  entry("kb-upload", "Insecure File Upload", "File Handling", "Upload processing accepts content or handling paths outside intended constraints.", "Describe data, service, or trust-boundary consequences observed within scope.", "Validate file type and content, isolate storage, and serve files safely."),
  entry("kb-logic", "Business Logic Issue", "Business Logic", "An intended workflow can be used in an unintended but authorized-testable sequence.", "Explain the business rule violation and measurable effect.", "Enforce invariant checks server-side and test critical workflow transitions."),
  entry("kb-session", "Session Management Weakness", "Session", "Session lifecycle or binding controls do not meet intended security expectations.", "Describe account or session exposure while avoiding unsafe credential handling.", "Use secure session rotation, expiry, binding, and cookie configuration."),
  entry("kb-api-auth", "API Authorization Issue", "API Authorization", "An API endpoint lacks an appropriate authorization decision.", "Describe affected data or operations across roles or tenants.", "Apply consistent resource and function authorization at API boundaries."),
  entry("kb-sensitive", "Sensitive Data Exposure", "Data Exposure", "Sensitive data is stored, transmitted, or returned without appropriate protection.", "Describe affected records, audiences, and realistic privacy or security consequences.", "Minimize data, apply access controls, and use appropriate transport and storage protections."),
  entry("kb-function-auth", "Missing Function-Level Authorization", "Authorization", "A protected function can be reached by a role that should not be permitted to perform it.", "Describe the unauthorized function, the tested role, and the observed server-side result without overstating downstream impact.", "Enforce role and permission checks at the server-side function boundary and include negative authorization tests."),
  entry("kb-tenant", "Cross-Tenant Data Access", "Authorization", "Tenant boundaries are not consistently enforced for a data object or workflow.", "Document the tested organizations, the affected object type, and only evidence-supported cross-tenant access or changes.", "Derive tenant scope from trusted server-side context and validate ownership for every object access."),
  entry("kb-password-reset", "Password Reset Flow Weakness", "Authentication", "A password-recovery workflow lacks an intended verification, expiry, binding, or state control.", "Describe the account-recovery consequence using controlled accounts; do not include live reset links or credentials.", "Use short-lived, single-use, account-bound recovery artifacts and verify state changes at the server side."),
  entry("kb-enumeration", "Account Enumeration", "Authentication", "Observable differences reveal whether an account identifier is present or valid.", "Describe the response difference and realistic privacy or targeting risk without claiming account compromise.", "Use consistent user-facing responses while retaining appropriate server-side monitoring and abuse controls."),
  entry("kb-cors", "CORS Misconfiguration", "Configuration", "Cross-origin policy grants an origin, method, header, or credential combination beyond the intended audience.", "Record the applicable origin and browser-visible behavior; distinguish a policy observation from confirmed cross-origin data access.", "Allow only explicit trusted origins and review credentialed cross-origin behavior with least privilege."),
  entry("kb-cache", "Cache-Control Weakness", "Configuration", "A response containing sensitive or personalized content may be stored or served contrary to its intended cache policy.", "Describe the response class, cache directives, and any safely observed sharing behavior.", "Set response-specific cache directives, vary correctly by authorization context, and validate intermediary behavior."),
  entry("kb-file-download", "File Access Control", "File Handling", "A file retrieval flow does not consistently enforce ownership, authorization, or safe path handling.", "Document the requested file class, tested authorization context, and redacted observed result.", "Authorize every retrieval server-side, map public identifiers to controlled storage records, and avoid trusting client paths."),
  entry("kb-mass-assignment", "Mass Assignment", "API Security", "A client-controlled property can influence a server-side field outside the intended API contract.", "Describe the documented versus accepted property set and the observed safe test result without including destructive field values.", "Use explicit allowlists or request DTOs and test that sensitive fields cannot be changed by untrusted clients."),
  entry("kb-graphql", "GraphQL Authorization", "API Security", "A GraphQL resolver or object field does not apply the authorization decision required for the requesting context.", "Identify the resolver or field, the authorized test context, and the redacted response difference.", "Apply authorization at resolver and object-field boundaries, with tests across roles and tenants."),
  entry("kb-business-state", "Business Rule and State Validation", "Business Logic", "A workflow transition or business invariant is accepted outside its intended state.", "Explain the expected workflow rule, the controlled sequence used, and the measurable observed outcome.", "Enforce invariants transactionally on the server side and add regression coverage for invalid state transitions."),
  entry("kb-client-storage", "Client-Side Sensitive Data", "Client-Side", "Sensitive information is retained in browser or application storage beyond the intended exposure boundary.", "Describe the storage location, data classification, and access context without recording live secrets.", "Avoid storing secrets client-side where possible; minimize retention and use platform-appropriate protected storage."),
  entry("kb-mobile-link", "Mobile Deep Link Validation", "Mobile", "A mobile deep link or exported component accepts input or navigation outside the intended authorization boundary.", "Document the tested app state, link form, and observed navigation without publishing target-specific attack recipes.", "Validate link parameters and authorization server-side, and restrict exported component exposure to necessary flows."),
  entry("kb-headers", "Security Headers", "Configuration", "Browser security headers are missing, overly broad, or inconsistent with the application’s intended protections.", "Record the affected response and explain the control gap in the relevant browser context.", "Set and test a deliberate header policy, including context-aware CSP, framing, transport, and caching controls."),
];
