import type { ReproductionStep } from "../../types/report";
import type {
  ReportTemplate,
  TemplateDifficulty,
  TemplateExample,
} from "../../types/template";

interface Definition {
  id: string;
  name: string;
  category: string;
  vulnerabilityClass: string;
  difficulty?: TemplateDifficulty;
  target?: string;
}
const step = (
  title: string,
  instruction: string,
  expectedResult: string,
  actualResult: string,
): ReproductionStep => ({
  id: `example-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  title,
  instruction,
  expectedResult,
  actualResult,
  evidenceIds: [],
});
const genericExample = (definition: Definition): TemplateExample => {
  const target =
    definition.target ??
    (definition.category === "API Security"
      ? "https://api.example.test"
      : definition.category === "File Handling"
        ? "https://files.example.test"
        : definition.category === "Business Logic"
          ? "https://shop.example.test"
          : "https://app.example.test");
  return {
    title: `${definition.name} observed in a fictional training feature`,
    programName: "Fictional Training Program",
    platform: "Other",
    target,
    vulnerableEndpoint: "/training/[FEATURE]",
    affectedAsset: "Fictional training application",
    vulnerabilityType: definition.name,
    vulnerabilityClass: definition.vulnerabilityClass,
    severity:
      definition.category === "Information Disclosure" ? "Medium" : "High",
    cvssScore: definition.category === "Information Disclosure" ? 5.3 : 7.1,
    cvssVector:
      definition.category === "Information Disclosure"
        ? "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
        : "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:N",
    summary: `During authorized testing of a fictional feature, ${definition.name.toLowerCase()} was observed when a controlled placeholder value was processed. Placeholder values such as [TEST_INPUT] are illustrative only.`,
    description: `The fictional application accepted a controlled test condition in the ${definition.name} workflow without the expected server-side or client-side safeguard. This example explains how to document the observed behavior without asserting impact beyond the evidence collected.`,
    prerequisites:
      "Authorized test access to the fictional training environment and a controlled test account. No passwords or live secrets are included.",
    structuredSteps: [
      step(
        "Review the authorized feature",
        "Open the fictional training feature and record its intended behavior.",
        "The feature should apply its documented safeguard.",
        "The feature is ready for a controlled observation.",
      ),
      step(
        "Use a controlled placeholder",
        "Provide [TEST_INPUT] or another harmless placeholder in the documented input or workflow.",
        "The placeholder should be handled according to the intended control.",
        "The observed behavior should be recorded without using destructive or exploit payloads.",
      ),
      step(
        "Capture the result",
        "Record the response, UI state, or configuration observation with sensitive values redacted.",
        "Only authorized and expected information should be returned.",
        `The result indicates a potential ${definition.name.toLowerCase()} condition that needs manual review.`,
      ),
    ],
    impact: `If confirmed in a real authorized environment, ${definition.name.toLowerCase()} could affect the confidentiality, integrity, or intended access boundary of the affected feature. This example does not claim compromise without supporting evidence.`,
    remediation: `Review the ${definition.name.toLowerCase()} control at the relevant trust boundary. Apply an appropriate server-side or client-side defensive control, add regression coverage, and manually verify the corrected behavior in an authorized environment.`,
    evidenceSuggestions: [
      "Redacted authorized request or screen recording",
      "Expected versus observed behavior notes",
      "Relevant configuration or response excerpt with secrets removed",
      "Scope and environment confirmation",
    ],
  };
};
const idorExample: TemplateExample = {
  title:
    "Authenticated user can access another user’s invoice by modifying the invoice identifier",
  programName: "Fictional Training Program",
  platform: "Other",
  target: "https://app.example.test",
  vulnerableEndpoint: "GET /api/invoices/[INVOICE_ID]",
  affectedAsset: "Invoice API",
  vulnerabilityType: "Broken Access Control / IDOR",
  vulnerabilityClass: "Authorization",
  severity: "High",
  cvssScore: 7.5,
  cvssVector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
  summary:
    "An authenticated user can retrieve invoice records belonging to another account by changing the invoice identifier in the request. The server returns the requested invoice without verifying that the authenticated user owns or is authorized to access it.",
  description:
    "The invoice endpoint uses an identifier supplied by the client. In this fictional educational example, Account A can substitute [OBJECT_ID_B] for its own [OBJECT_ID_A]. The response contains Account B’s invoice record. Values are placeholders and must be replaced with authorized evidence.",
  prerequisites:
    "Two authorized test accounts, Account A and Account B, each with a separate fictional invoice.",
  structuredSteps: [
    step(
      "Sign in as Account A",
      "Sign in to the fictional application as Account A.",
      "Account A can access only its own invoices.",
      "Account A session [SESSION_A] is active.",
    ),
    step(
      "Capture Account A invoice request",
      "Open an invoice owned by Account A and record the authorized request and [OBJECT_ID_A].",
      "The request identifies Account A’s invoice.",
      "The authorized invoice request is recorded.",
    ),
    step(
      "Record Account B identifier",
      "In a separate authorized session, sign in as Account B and record [OBJECT_ID_B] from its invoice.",
      "Account B’s identifier remains isolated from Account A.",
      "[OBJECT_ID_B] is recorded for controlled verification.",
    ),
    step(
      "Substitute the identifier",
      "Return to Account A’s authorized session and replace [OBJECT_ID_A] with [OBJECT_ID_B].",
      "The server should reject access because Account A does not own Account B’s invoice.",
      "The request is accepted for processing.",
    ),
    step(
      "Observe the response",
      "Record the returned fields with private values redacted.",
      "No Account B invoice data should be returned.",
      "The server returns invoice data belonging to Account B.",
    ),
  ],
  impact:
    "An authenticated attacker could access invoice data belonging to other users. Depending on returned fields, this may expose names, addresses, billing details, order information, or other private records.",
  remediation:
    "Enforce server-side object-level authorization for every invoice request. Verify that the requested invoice belongs to the authenticated account or that the user has an explicitly permitted administrative role.",
  evidenceSuggestions: [
    "Authorized request from Account A",
    "Authorized request from Account B",
    "Modified request using Account B’s identifier",
    "Response showing cross-account data",
    "Screenshot with private values redacted",
  ],
};
const reflectedXssExample: TemplateExample = {
  title: "Search term is reflected without context-aware output encoding",
  programName: "Fictional Training Program",
  platform: "Other",
  target: "https://app.example.test",
  vulnerableEndpoint: "GET /search?q=[TEST_INPUT]",
  affectedAsset: "Search results page",
  vulnerabilityType: "Reflected Cross-Site Scripting",
  vulnerabilityClass: "Injection",
  severity: "Medium",
  cvssScore: 6.1,
  cvssVector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
  summary:
    "A controlled marker supplied through the fictional search parameter is reflected into the search results page in an unsafe rendering context. This educational example uses [TEST_INPUT], not an exploit payload.",
  description:
    "The search page displays the supplied q parameter in the results heading. The controlled marker is reflected into markup without the expected context-aware output encoding. Record the exact rendering location and avoid including payload libraries or token-access examples.",
  prerequisites:
    "Access to the authorized fictional search page. [TEST_INPUT] is a harmless marker placeholder.",
  structuredSteps: [
    step(
      "Open search",
      "Open https://app.example.test/search in the fictional training environment.",
      "The page should display a search form and encode untrusted values safely.",
      "The search form is available.",
    ),
    step(
      "Enter a harmless marker",
      "Search for [TEST_INPUT].",
      "The marker should be rendered as plain text.",
      "The marker is reflected in the results heading.",
    ),
    step(
      "Inspect the rendering context",
      "Record where the marker appears in the rendered page and source context.",
      "Untrusted input should not be interpreted as markup or script.",
      "The observed context lacks the expected output encoding.",
    ),
    step(
      "Document safely",
      "Capture a redacted screenshot and the non-sensitive response excerpt.",
      "Evidence should show safe rendering or rejection.",
      "Evidence shows the marker’s unsafe rendering context.",
    ),
  ],
  impact:
    "If an attacker can cause another user to open a crafted link in the affected context, unsafe rendering may affect that user’s interaction with the page. The actual impact depends on browser controls, session protections, and the reachable page context.",
  remediation:
    "Apply context-aware output encoding for all untrusted values at the rendering sink. Validate input as appropriate and maintain a restrictive Content Security Policy as a defense in depth control.",
  evidenceSuggestions: [
    "Full fictional search URL with [TEST_INPUT]",
    "Screenshot showing the reflection location",
    "Rendered DOM or response excerpt",
    "Browser and environment details",
    "Redaction review confirming no tokens are visible",
  ],
};
const disclosureExample: TemplateExample = {
  title: "Profile API returns unnecessary internal metadata to a standard user",
  programName: "Fictional Training Program",
  platform: "Other",
  target: "https://api.example.test",
  vulnerableEndpoint: "GET /v1/profile",
  affectedAsset: "Profile API",
  vulnerabilityType: "Information Disclosure",
  vulnerabilityClass: "Data Exposure",
  severity: "Medium",
  cvssScore: 5.3,
  cvssVector: "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
  summary:
    "A fictional profile API returns internal record identifiers, environment labels, and debugging details that are not required by the client. The response does not include an active secret in this example.",
  description:
    "The authorized response includes user-facing profile data plus internal_record_id, deployment_environment, and diagnostic flags. The report distinguishes these potentially sensitive implementation details from harmless display metadata such as a public profile name.",
  prerequisites:
    "Authorized Standard User access to the fictional API and a redaction plan for captured responses.",
  structuredSteps: [
    step(
      "Authenticate as Standard User",
      "Use an authorized fictional Standard User session to request the profile endpoint.",
      "The response should contain only fields needed by the client.",
      "The authorized request succeeds.",
    ),
    step(
      "Review returned fields",
      "Compare response fields with the profile screen requirements.",
      "Internal operational fields should not be exposed unless required.",
      "The response includes internal identifiers, environment labels, and diagnostic details.",
    ),
    step(
      "Separate the exposure",
      "Document fields that are harmless display metadata separately from unnecessary internal fields.",
      "The report should avoid overstating the sensitivity of public information.",
      "Unnecessary internal metadata is identified and redacted in evidence.",
    ),
    step(
      "Record impact carefully",
      "Capture a redacted response excerpt.",
      "The report should state only evidence-supported consequences.",
      "The metadata could assist further research but does not prove compromise.",
    ),
  ],
  impact:
    "Internal identifiers, environment names, and debugging details may help an attacker understand application structure or target additional research. The observed metadata alone does not establish a guaranteed compromise.",
  remediation:
    "Minimize API response fields to the client contract, enforce field-level authorization where applicable, and disable verbose production diagnostics. Review response schemas and regression tests for unintended metadata.",
  evidenceSuggestions: [
    "Redacted profile API response",
    "Client screen showing required public fields",
    "Field-by-field comparison",
    "Environment and scope confirmation",
    "Screenshot with internal values redacted",
  ],
};
const definitions: Definition[] = [
  [
    "idor",
    "Broken Access Control / IDOR",
    "Access Control",
    "Authorization",
    "Beginner",
  ],
  [
    "function-auth",
    "Missing Function-Level Authorization",
    "Access Control",
    "Authorization",
    "Intermediate",
  ],
  [
    "privilege-escalation",
    "Privilege Escalation",
    "Access Control",
    "Authorization",
    "Intermediate",
  ],
  [
    "cross-tenant",
    "Cross-Tenant Data Access",
    "Access Control",
    "Authorization",
    "Advanced",
  ],
  [
    "file-auth",
    "Unauthorized File Access",
    "Access Control",
    "Authorization",
    "Intermediate",
  ],
  [
    "auth-bypass",
    "Authentication Bypass",
    "Authentication",
    "Authentication",
    "Advanced",
  ],
  [
    "account-enumeration",
    "Account Enumeration",
    "Authentication",
    "Authentication",
    "Beginner",
  ],
  [
    "password-reset",
    "Weak Password Reset Flow",
    "Authentication",
    "Authentication",
    "Intermediate",
  ],
  [
    "logout-session",
    "Session Not Invalidated After Logout",
    "Session Management",
    "Session Management",
    "Beginner",
  ],
  [
    "session-fixation",
    "Session Fixation",
    "Session Management",
    "Session Management",
    "Advanced",
  ],
  [
    "reauthentication",
    "Missing Reauthentication",
    "Authentication",
    "Authentication",
    "Intermediate",
  ],
  [
    "mfa-documentation",
    "Multi-Factor Authentication Bypass Documentation",
    "Authentication",
    "Authentication",
    "Advanced",
  ],
  [
    "remember-me",
    "Insecure Remember-Me Functionality",
    "Session Management",
    "Session Management",
    "Intermediate",
  ],
  [
    "reflected-xss",
    "Reflected Cross-Site Scripting",
    "Injection",
    "Injection",
    "Beginner",
  ],
  [
    "stored-xss",
    "Stored Cross-Site Scripting",
    "Injection",
    "Injection",
    "Intermediate",
  ],
  [
    "dom-xss",
    "DOM-Based Cross-Site Scripting",
    "Injection",
    "Injection",
    "Advanced",
  ],
  [
    "html-injection",
    "HTML Injection",
    "Injection",
    "Input Handling",
    "Beginner",
  ],
  [
    "sql-documentation",
    "SQL Injection Documentation",
    "Injection",
    "Input Handling",
    "Advanced",
  ],
  [
    "command-documentation",
    "Command Injection Documentation",
    "Injection",
    "Input Handling",
    "Advanced",
  ],
  [
    "ssti-documentation",
    "Server-Side Template Injection Documentation",
    "Injection",
    "Input Handling",
    "Advanced",
  ],
  [
    "xxe-documentation",
    "XML External Entity Documentation",
    "Injection",
    "Input Handling",
    "Advanced",
  ],
  ["crlf", "CRLF Injection", "Injection", "Input Handling", "Intermediate"],
  [
    "csv-formula",
    "CSV Formula Injection",
    "Injection",
    "Output Encoding",
    "Beginner",
  ],
  [
    "ssrf",
    "Server-Side Request Forgery",
    "Configuration",
    "Server-Side Request Forgery",
    "Advanced",
  ],
  [
    "open-redirect",
    "Open Redirect",
    "Configuration",
    "Input Handling",
    "Beginner",
  ],
  [
    "host-header",
    "Host Header Injection",
    "Configuration",
    "Configuration",
    "Advanced",
  ],
  [
    "cors",
    "CORS Misconfiguration",
    "Configuration",
    "Configuration",
    "Intermediate",
  ],
  [
    "cache-deception",
    "Web Cache Deception",
    "Configuration",
    "Configuration",
    "Advanced",
  ],
  [
    "cache-poisoning",
    "Web Cache Poisoning Documentation",
    "Configuration",
    "Configuration",
    "Advanced",
  ],
  [
    "request-smuggling",
    "HTTP Request Smuggling Documentation",
    "Configuration",
    "Infrastructure",
    "Advanced",
  ],
  [
    "proxy-config",
    "Insecure Proxy Configuration",
    "Configuration",
    "Infrastructure",
    "Intermediate",
  ],
  [
    "file-upload",
    "Insecure File Upload",
    "File Handling",
    "Input Handling",
    "Intermediate",
  ],
  [
    "file-download",
    "Unrestricted File Download",
    "File Handling",
    "Authorization",
    "Intermediate",
  ],
  [
    "path-traversal",
    "Path Traversal",
    "File Handling",
    "Input Handling",
    "Advanced",
  ],
  [
    "cloud-storage",
    "Public Cloud Storage Exposure",
    "File Handling",
    "Configuration",
    "Intermediate",
  ],
  [
    "backup-exposure",
    "Sensitive Backup File Exposure",
    "File Handling",
    "Information Disclosure",
    "Beginner",
  ],
  [
    "sourcemap",
    "Source Map Exposure",
    "File Handling",
    "Information Disclosure",
    "Beginner",
  ],
  [
    "config-file",
    "Exposed Configuration File",
    "File Handling",
    "Configuration",
    "Beginner",
  ],
  [
    "directory-listing",
    "Directory Listing Enabled",
    "File Handling",
    "Configuration",
    "Beginner",
  ],
  [
    "api-authz",
    "API Authorization Issue",
    "API Security",
    "Authorization",
    "Beginner",
  ],
  [
    "excessive-data",
    "Excessive Data Exposure",
    "API Security",
    "Data Exposure",
    "Beginner",
  ],
  [
    "mass-assignment",
    "Mass Assignment",
    "API Security",
    "Authorization",
    "Intermediate",
  ],
  [
    "api-rate-limit",
    "Missing API Rate Limiting",
    "API Security",
    "Configuration",
    "Intermediate",
  ],
  [
    "graphql-introspection",
    "GraphQL Introspection Exposure",
    "API Security",
    "Information Disclosure",
    "Beginner",
  ],
  [
    "graphql-authz",
    "GraphQL Authorization Issue",
    "API Security",
    "Authorization",
    "Intermediate",
  ],
  [
    "api-version",
    "API Version Exposure",
    "API Security",
    "Information Disclosure",
    "Beginner",
  ],
  [
    "undocumented-api",
    "Undocumented API Endpoint",
    "API Security",
    "Information Disclosure",
    "Intermediate",
  ],
  [
    "object-property",
    "Improper Object Property Authorization",
    "API Security",
    "Authorization",
    "Advanced",
  ],
  [
    "coupon",
    "Coupon or Discount Abuse",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "price-manipulation",
    "Quantity or Price Manipulation",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "workflow-bypass",
    "Workflow Bypass",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "duplicate-transaction",
    "Duplicate Transaction",
    "Business Logic",
    "Business Logic",
    "Advanced",
  ],
  [
    "race-documentation",
    "Race Condition Documentation",
    "Business Logic",
    "Business Logic",
    "Advanced",
  ],
  [
    "rate-limit-weakness",
    "Rate Limit Weakness",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "invitation-abuse",
    "Invitation Flow Abuse",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "referral-abuse",
    "Referral System Abuse",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "subscription-abuse",
    "Subscription or Trial Abuse",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "state-validation",
    "Missing State Validation",
    "Business Logic",
    "Business Logic",
    "Intermediate",
  ],
  [
    "information-disclosure",
    "Information Disclosure",
    "Information Disclosure",
    "Data Exposure",
    "Beginner",
  ],
  [
    "verbose-error",
    "Verbose Error Message",
    "Information Disclosure",
    "Information Disclosure",
    "Beginner",
  ],
  [
    "stack-trace",
    "Stack Trace Exposure",
    "Information Disclosure",
    "Information Disclosure",
    "Beginner",
  ],
  [
    "internal-host",
    "Internal IP or Hostname Disclosure",
    "Information Disclosure",
    "Information Disclosure",
    "Beginner",
  ],
  [
    "user-enumeration",
    "User Enumeration",
    "Information Disclosure",
    "Authentication",
    "Beginner",
  ],
  [
    "sensitive-metadata",
    "Sensitive Metadata Exposure",
    "Information Disclosure",
    "Data Exposure",
    "Intermediate",
  ],
  [
    "debug-endpoint",
    "Debug Endpoint Exposure",
    "Information Disclosure",
    "Configuration",
    "Intermediate",
  ],
  [
    "public-logs",
    "Publicly Accessible Logs",
    "Information Disclosure",
    "Data Exposure",
    "Intermediate",
  ],
  [
    "api-key-documentation",
    "API Key or Token Exposure Documentation",
    "Information Disclosure",
    "Data Exposure",
    "Advanced",
  ],
  [
    "security-misconfiguration",
    "Security Misconfiguration",
    "Configuration",
    "Configuration",
    "Beginner",
  ],
  [
    "security-headers",
    "Missing Security Headers",
    "Configuration",
    "Configuration",
    "Beginner",
  ],
  [
    "csp",
    "Weak Content Security Policy",
    "Configuration",
    "Configuration",
    "Intermediate",
  ],
  [
    "clickjacking",
    "Clickjacking",
    "Configuration",
    "Configuration",
    "Beginner",
  ],
  [
    "mixed-content",
    "Mixed Content",
    "Configuration",
    "Configuration",
    "Beginner",
  ],
  [
    "cookie-attributes",
    "Insecure Cookie Attributes",
    "Configuration",
    "Session Management",
    "Beginner",
  ],
  [
    "cache-control",
    "Improper Cache-Control",
    "Configuration",
    "Configuration",
    "Intermediate",
  ],
  [
    "admin-interface",
    "Exposed Admin Interface",
    "Configuration",
    "Configuration",
    "Intermediate",
  ],
  [
    "default-credentials",
    "Default Credentials Observation",
    "Configuration",
    "Configuration",
    "Intermediate",
  ],
  [
    "debug-mode",
    "Debug Mode Enabled",
    "Configuration",
    "Configuration",
    "Beginner",
  ],
  [
    "csrf",
    "Cross-Site Request Forgery",
    "Request Integrity",
    "Request Integrity",
    "Intermediate",
  ],
  [
    "origin-validation",
    "Missing Origin Validation",
    "Request Integrity",
    "Request Integrity",
    "Intermediate",
  ],
  [
    "anti-automation",
    "Missing Anti-Automation Control",
    "Request Integrity",
    "Request Integrity",
    "Intermediate",
  ],
  [
    "replayable-request",
    "Replayable Sensitive Request",
    "Request Integrity",
    "Request Integrity",
    "Intermediate",
  ],
  [
    "parameter-tampering",
    "Parameter Tampering",
    "Request Integrity",
    "Business Logic",
    "Intermediate",
  ],
  [
    "client-storage",
    "Sensitive Data Stored Client-Side",
    "Client-Side",
    "Data Exposure",
    "Beginner",
  ],
  [
    "hardcoded-secret",
    "Hardcoded Secret Observation",
    "Mobile",
    "Data Exposure",
    "Intermediate",
  ],
  ["deep-link", "Insecure Deep Link", "Mobile", "Mobile", "Intermediate"],
  [
    "exported-component",
    "Exported Mobile Component",
    "Mobile",
    "Mobile",
    "Intermediate",
  ],
  [
    "webview",
    "Insecure WebView Configuration",
    "Mobile",
    "Mobile",
    "Intermediate",
  ],
  [
    "client-authz",
    "Client-Side Authorization Reliance",
    "Client-Side",
    "Authorization",
    "Intermediate",
  ],
  ["blank", "Custom Blank Report", "General", "General", "Beginner"],
  [
    "generic-web",
    "Generic Web Vulnerability",
    "General",
    "General",
    "Beginner",
  ],
  [
    "generic-api",
    "Generic API Vulnerability",
    "General",
    "API Security",
    "Beginner",
  ],
  [
    "generic-mobile",
    "Generic Mobile Vulnerability",
    "General",
    "Mobile",
    "Beginner",
  ],
  [
    "security-observation",
    "Security Observation",
    "General",
    "General",
    "Beginner",
  ],
  [
    "informational",
    "Informational Finding",
    "General",
    "Information Disclosure",
    "Beginner",
  ],
  ["retest", "Retest Report", "General", "Remediation", "Beginner"],
  [
    "remediation-verification",
    "Remediation Verification Report",
    "General",
    "Remediation",
    "Beginner",
  ],
].map(([id, name, category, vulnerabilityClass, difficulty]) => ({
  id,
  name,
  category,
  vulnerabilityClass,
  difficulty: difficulty as TemplateDifficulty,
}));
function template(definition: Definition): ReportTemplate {
  const example =
    definition.id === "idor"
      ? idorExample
      : definition.id === "reflected-xss"
        ? reflectedXssExample
        : definition.id === "information-disclosure"
          ? disclosureExample
          : genericExample(definition);
  const sectionPrompts = {
    title: `State the affected feature and the observed ${definition.name.toLowerCase()} condition without exaggeration.`,
    summary: `Summarize the authorized observation, affected role or asset, and evidence-supported consequence for ${definition.name}.`,
    description: `Explain the relevant trust boundary, input or workflow, expected control, and observed behavior for ${definition.name}.`,
    prerequisites:
      "Identify the authorized scope, environment, account role, and harmless placeholders used during testing.",
    reproduction:
      "Use numbered, reproducible steps with expected and actual results. Do not include destructive payloads or live secrets.",
    impact: `Describe the realistic evidence-supported impact of ${definition.name} and distinguish confirmed behavior from assumptions.`,
    remediation: `Recommend a practical defensive control for ${definition.name}, plus regression testing and manual verification.`,
  };
  return {
    id: `builtin-${definition.id}`,
    name: definition.name,
    isBuiltIn: true,
    builtIn: true,
    category: definition.category,
    shortDescription: `A safe, structured reporting guide for documenting ${definition.name.toLowerCase()} in an authorized environment.`,
    difficulty: definition.difficulty ?? "Beginner",
    tags: [definition.category, definition.vulnerabilityClass, "documentation"],
    vulnerabilityType: definition.name,
    vulnerabilityClass: definition.vulnerabilityClass,
    sectionPrompts,
    evidenceChecklist: [...example.evidenceSuggestions],
    questionsToAnswer: [
      `What authorized feature or endpoint is affected by ${definition.name}?`,
      "Which user, role, tenant, or environment was used for the observation?",
      "What was the expected secure behavior?",
      "What did you actually observe, and how was it recorded?",
      "Which private values must be redacted before sharing evidence?",
      `What defensive control would address ${definition.name} at the correct boundary?`,
    ],
    commonMistakes: [
      "Claiming impact without evidence",
      "Omitting the affected role or environment",
      "Using vague reproduction steps",
      "Failing to distinguish expected from actual behavior",
      "Exposing tokens or private data in screenshots",
      "Reporting a theoretical condition as confirmed",
    ],
    example,
    relatedKnowledgeIds: [
      definition.vulnerabilityClass.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    ],
    summaryPrompt: sectionPrompts.summary,
    descriptionPrompt: sectionPrompts.description,
    impactPrompt: sectionPrompts.impact,
    remediationPrompt: sectionPrompts.remediation,
    reproductionSteps: [],
  };
}

export const BUILT_IN_TEMPLATES: ReportTemplate[] = definitions.map(template);
