import type { RetestRecord } from "../types/phase6";
import type { Report } from "../types/report";

export type ComparisonState = "Unchanged" | "Added" | "Removed" | "Modified" | "Not Available";
export interface ComparisonRow { label: string; original: string; current: string; state: ComparisonState; }
const clean = (value?: string) => value?.trim() || "";
function compare(label: string, original?: string, current?: string): ComparisonRow { const left = clean(original); const right = clean(current); return { label, original: left || "Not available", current: right || "Not available", state: !left && !right ? "Not Available" : !left ? "Added" : !right ? "Removed" : left === right ? "Unchanged" : "Modified" }; }
export function createRemediationComparison(report: Report, retest: RetestRecord): ComparisonRow[] { const originalSteps = report.structuredSteps.length ? report.structuredSteps.map((step, index) => `${index + 1}. ${step.instruction}`).join("\n") : report.reproductionSteps; return [compare("Target", report.target || report.affectedAsset, retest.targetSnapshot), compare("Vulnerable endpoint", report.vulnerableEndpoint, undefined), compare("Reproduction steps", originalSteps, retest.notes), compare("Observed behavior", report.structuredSteps.map((step) => step.actualResult).filter(Boolean).join("\n") || report.evidence, retest.currentBehavior), compare("Impact / residual impact", report.impact, retest.residualRisk), compare("Evidence", report.evidenceItems.map((item) => item.title).join(", "), retest.evidenceIds.length ? `${retest.evidenceIds.length} linked evidence item(s)` : ""), compare("CVSS and severity", `${report.severity} (${report.cvssScore})`, `${report.severity} (${report.cvssScore})`), compare("Build or version", "", retest.buildOrVersion)]; }
export function comparisonMarkdown(report: Report, retest: RetestRecord): string { const rows = createRemediationComparison(report, retest); return `# Remediation Comparison — ${report.title || report.reportReference}\n\nObserved during retest. This comparison does not independently establish remediation effectiveness without explicit researcher confirmation.\n\n| Area | Original | Observed during retest | Change |\n| --- | --- | --- | --- |\n${rows.map((row) => `| ${row.label} | ${row.original.replace(/\|/g, "\\|")} | ${row.current.replace(/\|/g, "\\|")} | ${row.state} |`).join("\n")}\n\nVerification outcome: ${retest.verificationOutcome}\n`; }
