import type { ReportTemplate, TemplateDifficulty, TemplateExample, TemplateSectionPrompts } from "../types/template";
import type { ReproductionStep } from "../types/report";

export const TEMPLATE_STORAGE_KEY = "bug-bounty-report-templates";
const difficultyValues: TemplateDifficulty[] = ["Beginner", "Intermediate", "Advanced"];
const strings = (value: unknown): string[] => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && Boolean(item.trim())).map((item) => item.trim()) : [];
const text = (value: unknown): string => typeof value === "string" ? value : "";
function prompts(source: Record<string, unknown>): TemplateSectionPrompts { const value = source.sectionPrompts && typeof source.sectionPrompts === "object" ? source.sectionPrompts as Record<string, unknown> : {}; return { title: text(value.title), summary: text(value.summary) || text(source.summaryPrompt), description: text(value.description) || text(source.descriptionPrompt), prerequisites: text(value.prerequisites), reproduction: text(value.reproduction), impact: text(value.impact) || text(source.impactPrompt), remediation: text(value.remediation) || text(source.remediationPrompt) }; }
function steps(value: unknown): ReproductionStep[] { return Array.isArray(value) ? value.flatMap((item) => { if (!item || typeof item !== "object") return []; const source = item as Partial<ReproductionStep>; if (typeof source.instruction !== "string") return []; return [{ id: typeof source.id === "string" ? source.id : crypto.randomUUID(), title: typeof source.title === "string" ? source.title : "", instruction: source.instruction, expectedResult: typeof source.expectedResult === "string" ? source.expectedResult : undefined, actualResult: typeof source.actualResult === "string" ? source.actualResult : undefined, evidenceIds: strings(source.evidenceIds) }]; }) : []; }
function example(value: unknown): TemplateExample | undefined { if (!value || typeof value !== "object") return undefined; const source = value as Record<string, unknown>; if (!text(source.title) || !text(source.summary) || !text(source.description) || !text(source.impact) || !text(source.remediation)) return undefined; return { title: text(source.title), programName: text(source.programName) || undefined, platform: text(source.platform) || undefined, target: text(source.target) || undefined, vulnerableEndpoint: text(source.vulnerableEndpoint) || undefined, affectedAsset: text(source.affectedAsset) || undefined, vulnerabilityType: text(source.vulnerabilityType), vulnerabilityClass: text(source.vulnerabilityClass) || undefined, severity: ["Informational", "Low", "Medium", "High", "Critical"].includes(text(source.severity)) ? text(source.severity) as TemplateExample["severity"] : undefined, cvssScore: typeof source.cvssScore === "number" && source.cvssScore >= 0 && source.cvssScore <= 10 ? source.cvssScore : undefined, cvssVector: text(source.cvssVector) || undefined, summary: text(source.summary), description: text(source.description), prerequisites: text(source.prerequisites) || undefined, structuredSteps: steps(source.structuredSteps), impact: text(source.impact), remediation: text(source.remediation), evidenceSuggestions: strings(source.evidenceSuggestions), references: Array.isArray(source.references) ? source.references.filter((item): item is NonNullable<TemplateExample["references"]>[number] => Boolean(item) && typeof item === "object" && typeof (item as { url?: unknown }).url === "string") : undefined, disclosureTimeline: Array.isArray(source.disclosureTimeline) ? source.disclosureTimeline.filter((item): item is NonNullable<TemplateExample["disclosureTimeline"]>[number] => Boolean(item) && typeof item === "object" && typeof (item as { event?: unknown }).event === "string") : undefined }; }

export function normalizeTemplate(value: unknown, builtIn = false): ReportTemplate | undefined {
  if (!value || typeof value !== "object") return undefined; const source = value as Record<string, unknown>;
  if (!text(source.id) || !text(source.name)) return undefined;
  const sectionPrompts = prompts(source); const isBuiltIn = builtIn || source.isBuiltIn === true || source.builtIn === true;
  return { id: text(source.id), name: text(source.name), isBuiltIn, builtIn: isBuiltIn, category: text(source.category) || "General", shortDescription: text(source.shortDescription) || text(source.descriptionPrompt) || "Structured writing guidance for an authorized security finding.", difficulty: difficultyValues.includes(text(source.difficulty) as TemplateDifficulty) ? text(source.difficulty) as TemplateDifficulty : "Beginner", tags: strings(source.tags), vulnerabilityType: text(source.vulnerabilityType), vulnerabilityClass: text(source.vulnerabilityClass), sectionPrompts, evidenceChecklist: strings(source.evidenceChecklist), questionsToAnswer: strings(source.questionsToAnswer), commonMistakes: strings(source.commonMistakes), example: example(source.example), relatedKnowledgeIds: strings(source.relatedKnowledgeIds), summaryPrompt: text(source.summaryPrompt) || sectionPrompts.summary || "", descriptionPrompt: text(source.descriptionPrompt) || sectionPrompts.description || "", impactPrompt: text(source.impactPrompt) || sectionPrompts.impact || "", remediationPrompt: text(source.remediationPrompt) || sectionPrompts.remediation || "", reproductionSteps: steps(source.reproductionSteps), createdAt: text(source.createdAt) || undefined, updatedAt: text(source.updatedAt) || undefined };
}

export function loadCustomTemplates(): ReportTemplate[] { try { const parsed: unknown = JSON.parse(window.localStorage.getItem(TEMPLATE_STORAGE_KEY) ?? "[]"); return Array.isArray(parsed) ? parsed.flatMap((item) => { const template = normalizeTemplate(item); return template ? [{ ...template, isBuiltIn: false, builtIn: false }] : []; }) : []; } catch { return []; } }
export function saveCustomTemplates(templates: ReportTemplate[]): void { window.localStorage.setItem(TEMPLATE_STORAGE_KEY, JSON.stringify(templates.map((template) => ({ ...template, isBuiltIn: false, builtIn: false, sectionPrompts: template.sectionPrompts ?? { summary: template.summaryPrompt, description: template.descriptionPrompt, impact: template.impactPrompt, remediation: template.remediationPrompt } })))); }
